# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcc1d39122498c03b257b1c72d4ed91897ab715958d3bce9c68d4c7e682e3a9e320f5d094cedb8c90fc4a7b5ca709dfed03172116c3771e2eacf50a7292085f6

test:
  secret_key_base: 041630212cd7e88ab97aadf4f876db70a0b282027d88ee11de79a4f0339463dd1b44942843e74de9aecc7c225dae509f722842118e925bb5384e5c0aa85a6ccc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
